addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"      % "0.14.4")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"    % "1.11.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"       % "0.6.4")
addSbtPlugin("dev.zio"          % "zio-sbt-ci"        % "0.4.0-alpha.34")
addSbtPlugin("dev.zio"          % "zio-sbt-ecosystem" % "0.4.0-alpha.34")
addSbtPlugin("dev.zio"          % "zio-sbt-website"   % "0.4.0-alpha.34")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"      % "2.5.5")

addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"      % "2.3.1")
